Fix module display_intf_headers dependency
error: hardware/qcom-caf/sdm660/display/Android.bp:18:1: display_headers depends on undefined module display_intf_headers
Module display_headers is defined in namespace . which can read these 10 namespaces: [. . vendor/qcom/opensource/dataservices hardware/google/pixel vendor/qcom/opensource/data-ipa-cfg-mgr-legacy-um device/asus/sdm660-common vendor/asus/X01BD vendor/asus/sdm660-common hardware/google/interfaces device/asus/sdm660-common/qcom-caf]
Module display_intf_headers can be found in these namespaces: [hardware/qcom-caf/msm8996 hardware/qcom-caf/msm8998 hardware/qcom/display/msm8909 hardware/qcom/sdm845 vendor/qcom/opensource/commonsys-intf/display]

Signed-off-by: khirendra03 <khirendrapatel3@gmail.com>